# Generated by Django 2.0.7 on 2018-08-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_bhk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='title',
        ),
    ]
