# Generated by Django 2.0.7 on 2018-08-29 12:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180808_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bhk',
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='post',
            name='timings',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='venue',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
