# Generated by Django 2.0.7 on 2018-08-29 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180829_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='event_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='timings',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 12, 51, 14, 49007, tzinfo=utc)),
        ),
    ]
