# Generated by Django 2.0.7 on 2018-08-29 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180829_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timings',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
