# Generated by Django 2.0.7 on 2018-09-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20180829_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('i', 'informal'), ('f', 'informal')], default='i', max_length=1),
            preserve_default=False,
        ),
    ]
