# Generated by Django 2.0.7 on 2018-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('i', 'informal'), ('f', 'formal')], max_length=1),
        ),
    ]
