# Generated by Django 2.0.7 on 2018-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20180909_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('i', 'Informal'), ('f', 'Formal')], default='i', max_length=1),
        ),
    ]
