# Generated by Django 2.0.7 on 2018-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180714_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dept',
            field=models.CharField(choices=[('sas', 'School of Advanced Sciences'), ('scse', 'School of Computing Science and Engineering'), ('select', 'School of Electrical Engineering '), ('sense', 'School of Electronics Engineering'), ('smbs', 'School of Mechanical and Building Sciences'), ('vitbs', 'VIT Business School'), ('vitsol', 'VIT School of Law'), ('vfit', 'VIT Fashion Institute of Technology')], default='', max_length=7),
        ),
    ]
