# Generated by Django 2.0.7 on 2018-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180714_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
