# Generated by Django 2.0.7 on 2018-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180714_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
