# Generated by Django 2.0.7 on 2018-07-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180716_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
