# Generated by Django 2.0.7 on 2018-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180717_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='pic',
        ),
        migrations.AddField(
            model_name='faculty',
            name='dp',
            field=models.ImageField(blank=True, upload_to='facultydps'),
        ),
    ]
