# Generated by Django 2.0.7 on 2018-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180718_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='v_or_c',
            field=models.CharField(choices=[('v', 'vellore'), ('c', 'chennai')], default='c', max_length=1),
        ),
    ]
