# Generated by Django 2.0.7 on 2018-07-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_faculty_v_or_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='v_or_c',
            new_name='campus',
        ),
    ]
