# Generated by Django 2.0.7 on 2018-11-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180724_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dept',
            field=models.CharField(choices=[('sas', 'School of Advanced Sciences'), ('scse', 'School of Computing Science and Engineering')], default='', max_length=7),
        ),
    ]
