# Generated by Django 2.0.7 on 2018-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20181108_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='direction',
            field=models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')]),
        ),
    ]
