# Generated by Django 2.0.7 on 2018-11-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20181108_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='dislikes',
        ),
    ]
