# Generated by Django 2.0.7 on 2018-11-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_faculty_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='direction',
            field=models.SmallIntegerField(choices=[(1, 'like'), (0, 'dislike')]),
        ),
    ]
