# Generated by Django 2.0.7 on 2018-11-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181108_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='rating',
        ),
        migrations.AlterField(
            model_name='like',
            name='direction',
            field=models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')]),
        ),
    ]
