# Generated by Django 2.0.7 on 2018-10-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20181020_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created', 'modified')},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
