# Generated by Django 2.0.7 on 2018-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20181020_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
