# Generated by Django 2.0.7 on 2018-10-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_answer_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
