# Generated by Django 2.0.7 on 2018-11-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_auto_20181024_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'get_latest_by': 'modified', 'ordering': ('-created', 'modified')},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'get_latest_by': 'modified', 'ordering': ('-created', 'modified', 'upvotes')},
        ),
    ]
